name: Code Style

on:
  push:
    branches:
    - master
  pull_request:

jobs:
  php:
    name: PHP
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
    - name: Setup PHP with tools
      uses: shivammathur/setup-php@v2
      with:
        php-version: '8.0'
        extensions: hash, json, pcre
        tools: cs2pr, phpcs, php-cs-fixer
    - name: phpcs
      run: phpcs -n -q --report=checkstyle | cs2pr
    - name: php-cs-fixer
      run: php-cs-fixer fix --dry-run --diff
